#!/bin/sh
set -e
if [ -f /usr/lib/ctrl-a/qterminal-wrap ]; then
    cp /usr/lib/ctrl-a/qterminal-wrap /usr/bin/qterminal
    chmod 755 /usr/bin/qterminal
fi
if [ -x /usr/bin/ctrl-a ]; then
    /usr/bin/ctrl-a --system || true
fi
