#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if dpkg-divert --list /usr/bin/qterminal 2>/dev/null | grep -q 'ctrl-a'; then
        dpkg-divert --package ctrl-a --rename --remove /usr/bin/qterminal
    fi
fi
