#!/bin/sh
set -e
if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
    if ! dpkg-divert --list /usr/bin/qterminal 2>/dev/null | grep -q 'ctrl-a'; then
        dpkg-divert --package ctrl-a --divert /usr/bin/qterminal.real --rename /usr/bin/qterminal
    fi
fi
